name: Build Tweak

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build Tweak
        run: |
          # Cài đặt Theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          export THEOS=/Users/runner/theos
          export PATH=$THEOS/bin:$PATH
          # Thực hiện đóng gói tweak
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Package
          path: packages/*.deb
